env = Environment()

SConscript('../data/SConscript')
SConscript('../risk/SConscript')

env.Append(LIBPATH=['../data', '../risk'])
env.Append(CPPPATH=['../data', '../risk'])
env.Append(LIBS=['data', 'risk'])

env.Program(target='bin/test_addPositions', source=['test_addPositions.cpp'])
