env = Environment()


env.Append(CCFLAGS=['-std=c++0x'])

env.Append(CPPPATH=['/usr/local/include'])
env.Append(CPPPATH=['../util'])
env.Append(CPPPATH=['../data'])

srcs = ['exchorder.cpp', 'simexchange.cpp']

env.StaticLibrary('trading', srcs)
